config/routes.rb
Rails.application.routes.draw do
  resources :boards
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :board
end

app/controllers/Boards_controller.rb
class BoardsController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token
  def index
    render json: Board.where(board_params)
  end

  def show
    render json: Board.find(params[:id])
  end

  def create
    if board = Board.create(board_params)
      render json: board
    else
      render json: board.errors.full_messages
    end
  end

  def update
    if board = Board.find(board_params[:id]).update(board_params)
      render json: board
    else
      render json: board.errors.full_messages
    end
  end

  def destroy
    render json: Board.find(params[:id]).destroy
  end

  private
  def board_params
    params.permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token
  def index
    render json: Item.where(item_params)
  end

  def show
    render json: Item.find(params[:id])
  end

  def create
    if item = Item.create(item_params)
      render json: item
    else
      render json: item.errors.full_messages
    end
  end

  def update
    if item = Item.find(item_params[:id]).update(item_params)
      render json: item
    else
      render json: item.errors.full_messages
    end
  end

  def destroy
    render json: Item.find(params[:id]).destroy
  end

  private
  def item_params
    params.permit(:task_name, :priority, :board_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_name %>
    <%= form.text_field :task_name %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.text_field :priority %>
  </div>

  <div class="field">
    <%= form.label :board_id %>
    <%= form.text_field :board_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Task name</th>
      <th>Priority</th>
      <th>Board</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.task_name %></td>
        <td><%= item.priority %></td>
        <td><%= item.board %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task name:</strong>
  <%= @item.task_name %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @item.priority %>
</p>

<p>
  <strong>Board:</strong>
  <%= @item.board %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsListV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>